@Test public void testClientCertSuccessfulAuth() throws Exception {
  makeCall("test client",200);
}
